#ifndef __DCA_MODULE_EXT_MEMORYMAP_OFFSET_H__
#define __DCA_MODULE_EXT_MEMORYMAP_OFFSET_H__

// reg dca_downsampler_inst
#define BW_DCA_DOWNSAMPLER_INST 352

// reg dca_downsampler_log
#define BW_DCA_DOWNSAMPLER_LOG 32

// reg dca_downsampler_status
#define BW_DCA_DOWNSAMPLER_STATUS 32

// reg dca_downsampler_opcode
#define BW_DCA_DOWNSAMPLER_OPCODE 6
#define DCA_DOWNSAMPLER_OPCODE_TOPLEFT 1
#define DCA_DOWNSAMPLER_OPCODE_MAX 2
#define DCA_DOWNSAMPLER_OPCODE_AVG 4
#define DCA_DOWNSAMPLER_OPCODE_SUM 8
#define DCA_DOWNSAMPLER_OPCODE_LSU0_REQ 16
#define DCA_DOWNSAMPLER_OPCODE_LSU1_REQ 32
#define DCA_DOWNSAMPLER_OPCODE_INDEX_TOPLEFT 0
#define DCA_DOWNSAMPLER_OPCODE_INDEX_MAX 1
#define DCA_DOWNSAMPLER_OPCODE_INDEX_AVG 2
#define DCA_DOWNSAMPLER_OPCODE_INDEX_SUM 3
#define DCA_DOWNSAMPLER_OPCODE_INDEX_LSU0_REQ 4
#define DCA_DOWNSAMPLER_OPCODE_INDEX_LSU1_REQ 5
#define DCA_DOWNSAMPLER_OPCODE_NONE 0

// reg dca_downsampler_inst_stride_onehot
#define BW_DCA_DOWNSAMPLER_INST_STRIDE_ONEHOT 8

#endif