// MATRIX_SIZE_PARA

localparam MATRIX_SIZE_PARA_0_AFTER = MATRIX_SIZE_PARA;

localparam MATRIX_SIZE_PARA_1_ANDSOON = MATRIX_SIZE_PARA_0_AFTER;
localparam MATRIX_SIZE_PARA_1_AFTER = MATRIX_SIZE_PARA_1_ANDSOON / MATRIX_SIZE_PARA_SEPARATOR;
localparam MATRIX_NUM_COL = MATRIX_SIZE_PARA_1_ANDSOON % MATRIX_SIZE_PARA_SEPARATOR;

localparam MATRIX_SIZE_PARA_2_ANDSOON = MATRIX_SIZE_PARA_1_AFTER;
localparam MATRIX_SIZE_PARA_2_AFTER = MATRIX_SIZE_PARA_2_ANDSOON / MATRIX_SIZE_PARA_SEPARATOR;
localparam _MATRIX_NUM_ROW_TEMP = MATRIX_SIZE_PARA_2_ANDSOON % MATRIX_SIZE_PARA_SEPARATOR;
localparam MATRIX_NUM_ROW = (_MATRIX_NUM_ROW_TEMP==0)? MATRIX_NUM_COL : _MATRIX_NUM_ROW_TEMP;

// extension

localparam MATRIX_MAX_DIM = (MATRIX_NUM_COL>=MATRIX_NUM_ROW)? MATRIX_NUM_COL : MATRIX_NUM_ROW;
localparam MATRIX_NUM_ELEMENT = MATRIX_NUM_COL*MATRIX_NUM_ROW;
