#ifndef __STARC_MEMORYMAP_OFFSET_H__
#define __STARC_MEMORYMAP_OFFSET_H__



// reg starc_inst
#define BW_STARC_INST 520

// reg starc_log
#define BW_STARC_LOG 32

// reg starc_status
#define BW_STARC_STATUS 32

// reg num_spike_allowed
#define BW_NUM_SPIKE_ALLOWED 15

// reg num_step_merged
#define BW_NUM_STEP_MERGED 16

// reg starc_neuron_state
#define BW_STARC_NEURON_STATE 7
#define STARC_NEURON_STATE_IDLE 1
#define STARC_NEURON_STATE_INIT_CLEAR 2
#define STARC_NEURON_STATE_INIT_THRE 4
#define STARC_NEURON_STATE_STIMULATE 8
#define STARC_NEURON_STATE_COMPARE 16
#define STARC_NEURON_STATE_FIRE 32
#define STARC_NEURON_STATE_THRE 64
#define STARC_NEURON_STATE_INDEX_IDLE 0
#define STARC_NEURON_STATE_INDEX_INIT_CLEAR 1
#define STARC_NEURON_STATE_INDEX_INIT_THRE 2
#define STARC_NEURON_STATE_INDEX_STIMULATE 3
#define STARC_NEURON_STATE_INDEX_COMPARE 4
#define STARC_NEURON_STATE_INDEX_FIRE 5
#define STARC_NEURON_STATE_INDEX_THRE 6
#define STARC_NEURON_STATE_NONE 0

// reg starc_acc_state
#define BW_STARC_ACC_STATE 3
#define STARC_ACC_STATE_FILL 1
#define STARC_ACC_STATE_CHECK_HALF 2
#define STARC_ACC_STATE_FOLD 4
#define STARC_ACC_STATE_INDEX_FILL 0
#define STARC_ACC_STATE_INDEX_CHECK_HALF 1
#define STARC_ACC_STATE_INDEX_FOLD 2
#define STARC_ACC_STATE_NONE 0

// reg neuron_reset_type
#define BW_NEURON_RESET_TYPE 1
#define NEURON_RESET_TYPE_HARD 0
#define NEURON_RESET_TYPE_SOFT 1
#define NEURON_RESET_TYPE_INDEX_SOFT 0

// reg starc_inst_opcode
#define BW_STARC_INST_OPCODE 3
#define STARC_INST_OPCODE_CLEAR_CAP 1
#define STARC_INST_OPCODE_LOAD_WEIGHT 2
#define STARC_INST_OPCODE_EXEC_LAYER 4
#define STARC_INST_OPCODE_INDEX_CLEAR_CAP 0
#define STARC_INST_OPCODE_INDEX_LOAD_WEIGHT 1
#define STARC_INST_OPCODE_INDEX_EXEC_LAYER 2
#define STARC_INST_OPCODE_NONE 0

// reg starc_blocked_step_inst_opcode
#define BW_STARC_BLOCKED_STEP_INST_OPCODE 5
#define STARC_BLOCKED_STEP_INST_OPCODE_IS_LAST_BLOCK_OF_SINGLE_STEP 1
#define STARC_BLOCKED_STEP_INST_OPCODE_IS_LAST_BLOCK_OF_MERGED_STEP 2
#define STARC_BLOCKED_STEP_INST_OPCODE_IS_FIRST_ACC 4
#define STARC_BLOCKED_STEP_INST_OPCODE_IS_FIRST_BLOCK_OF_ALL_STEPS 8
#define STARC_BLOCKED_STEP_INST_OPCODE_IS_LAST_BLOCK_OF_ALL_STEPS 16
#define STARC_BLOCKED_STEP_INST_OPCODE_INDEX_IS_LAST_BLOCK_OF_SINGLE_STEP 0
#define STARC_BLOCKED_STEP_INST_OPCODE_INDEX_IS_LAST_BLOCK_OF_MERGED_STEP 1
#define STARC_BLOCKED_STEP_INST_OPCODE_INDEX_IS_FIRST_ACC 2
#define STARC_BLOCKED_STEP_INST_OPCODE_INDEX_IS_FIRST_BLOCK_OF_ALL_STEPS 3
#define STARC_BLOCKED_STEP_INST_OPCODE_INDEX_IS_LAST_BLOCK_OF_ALL_STEPS 4
#define STARC_BLOCKED_STEP_INST_OPCODE_NONE 0

#endif