// DOWNSAMPLER_PARA
// NOTE: kernel 2x2, stride 2
localparam BW_BLOCKED_STEP_INST = MATRIX_MAX_DIM + MATRIX_NUM_ROW + MATRIX_NUM_COL + 1 + 1 + 1 + 1 + MATRIX_MAX_DIM + `BW_DCA_DOWNSAMPLER_OPCODE;

localparam integer DOWNSAMPLE_STRIDE = 2;
localparam integer OUT_MATRIX_NUM_ROW = (MATRIX_NUM_ROW/DOWNSAMPLE_STRIDE);
localparam integer OUT_MATRIX_NUM_COL = (MATRIX_NUM_COL/DOWNSAMPLE_STRIDE);

