`ifndef __DCA_MODULE_EXT_MEMORYMAP_OFFSET_H__
`define __DCA_MODULE_EXT_MEMORYMAP_OFFSET_H__

// reg dca_downsampler_inst
//`define BW_DCA_DOWNSAMPLER_INST 352
`define BW_DCA_DOWNSAMPLER_INST 326
`define DCA_DOWNSAMPLER_INST_DEFAULT_VALUE 0

// reg dca_downsampler_log
`define BW_DCA_DOWNSAMPLER_LOG 32
`define DCA_DOWNSAMPLER_LOG_DEFAULT_VALUE 0

// reg dca_downsampler_status
`define BW_DCA_DOWNSAMPLER_STATUS 32
`define DCA_DOWNSAMPLER_STATUS_DEFAULT_VALUE 0

// reg dca_downsampler_opcode
`define BW_DCA_DOWNSAMPLER_OPCODE 6
`define DCA_DOWNSAMPLER_OPCODE_DEFAULT_VALUE 0
`define DCA_DOWNSAMPLER_OPCODE_TOPLEFT 1
`define DCA_DOWNSAMPLER_OPCODE_MAX 2
`define DCA_DOWNSAMPLER_OPCODE_AVG 4
`define DCA_DOWNSAMPLER_OPCODE_SUM 8
`define DCA_DOWNSAMPLER_OPCODE_LSU0_REQ 16
`define DCA_DOWNSAMPLER_OPCODE_LSU1_REQ 32
`define DCA_DOWNSAMPLER_OPCODE_INDEX_TOPLEFT 0
`define DCA_DOWNSAMPLER_OPCODE_INDEX_MAX 1
`define DCA_DOWNSAMPLER_OPCODE_INDEX_AVG 2
`define DCA_DOWNSAMPLER_OPCODE_INDEX_SUM 3
`define DCA_DOWNSAMPLER_OPCODE_INDEX_LSU0_REQ 4
`define DCA_DOWNSAMPLER_OPCODE_INDEX_LSU2_REQ 5
`define DCA_DOWNSAMPLER_OPCODE_NONE 0

// reg dca_downsampler_inst_stride_onehot
`define BW_DCA_DOWNSAMPLER_INST_STRIDE_ONEHOT 8
`define DCA_DOWNSAMPLER_INST_STRIDE_ONEHOT_DEFAULT_VALUE 0

// reg matrix_info_flags (is_signed, is_float, addr_lsa_p3, bit_offset, is_binary)
`define BW_DCA_MATRIX_INFO_FLAGS 32
`define DCA_MATRIX_INFO_FLAGS 0

`endif 