`ifdef INCLUDE_HDMI
    ,.HDMI_I2C_SCL(HDMI_I2C_SCL)
    ,.HDMI_I2C_SDA(HDMI_I2C_SDA)
`endif

`ifdef INCLUDE_VIM
    ,.HDMI_RX_DCK(HDMI_RX_DCK)
    ,.HDMI_RX_HS(HDMI_RX_HS)
    ,.HDMI_RX_DE(HDMI_RX_DE)
    ,.HDMI_RX_VS(HDMI_RX_VS)
    ,.HDMI_RX_RST_N(HDMI_RX_RST_N)
    ,.HDMI_RX_VD(HDMI_RX_VD)
    ,.HDMI_RX_AMCLK(HDMI_RX_AMCLK)
    ,.HDMI_RX_ASCLK(HDMI_RX_ASCLK)
    ,.HDMI_RX_AP(HDMI_RX_AP)

    ,.CIS_I2C_SCL(CIS_I2C_SCL)
    ,.CIS_I2C_SDA(CIS_I2C_SDA)

    ,.CIS_MCLK(CIS_MCLK)
    ,.CIS_PCLK(CIS_PCLK)
    ,.CIS_RESET_N(CIS_RESET_N)
    ,.CIS_VS(CIS_VS)
    ,.CIS_HS(CIS_HS)
    ,.CIS_PD_N(CIS_PD_N)
    ,.CIS_D(CIS_D)
`endif

`ifdef INCLUDE_VOM
    ,.HDMI_TX_DCK(HDMI_TX_DCK)
    ,.HDMI_TX_DE(HDMI_TX_DE)
    ,.HDMI_TX_HS(HDMI_TX_HS)
    ,.HDMI_TX_VS(HDMI_TX_VS)
    ,.HDMI_TX_RST_N(HDMI_TX_RST_N)
    ,.HDMI_TX_VD(HDMI_TX_VD)

    ,.HDMI_TX_AO_MCLK(HDMI_TX_AO_MCLK)
    ,.HDMI_TX_AO_SCK(HDMI_TX_AO_SCK)
    ,.HDMI_TX_AO_WS(HDMI_TX_AO_WS)
    ,.HDMI_TX_AO_SD(HDMI_TX_AO_SD)
    ,.HDMI_TX_AO_SPDIF(HDMI_TX_AO_SPDIF)
`endif

`ifdef INCLUDE_TFT_LCD
    ,.LCD_DCLK(LCD_DCLK)
    ,.LCD_HS(LCD_HS)
    ,.LCD_VS(LCD_VS)
    ,.LCD_DE(LCD_DE)
    ,.LCD_RST_N(LCD_RST_N)
    ,.LCD_PWM(LCD_PWM)
    ,.LCD_BD(LCD_BD)
    ,.LCD_GD(LCD_GD)
    ,.LCD_RD(LCD_RD)
`endif

`ifdef INCLUDE_SPI_LCD
    ,.SPI_LCD_PD_N(SPI_LCD_PD_N)
`endif
