# total
set ::BW_MMAP_OFFSET_ERVP_JTAG 5
set ::ERVP_JTAG_ADDR_INTERVAL 8
set ::BW_UNUSED_ERVP_JTAG 3
set ::NUM_ERVP_JTAG_SUBMODULE 1

# submodule jtag
set ::MMAP_SUBOFFSET_JTAG_INST 0x0
set ::MMAP_SUBOFFSET_JTAG_REQUEST 0x8
set ::MMAP_SUBOFFSET_JTAG_RESPONSE 0x10

set ::MMAP_OFFSET_JTAG_INST ($MMAP_SUBOFFSET_JTAG_INST)
set ::MMAP_OFFSET_JTAG_REQUEST ($MMAP_SUBOFFSET_JTAG_REQUEST)
set ::MMAP_OFFSET_JTAG_RESPONSE ($MMAP_SUBOFFSET_JTAG_RESPONSE)

# reg jtag.inst
set ::BW_JTAG_INST 4
set ::JTAG_INST_EXTEST 0
set ::JTAG_INST_RESERVED 1
set ::JTAG_INST_IDCODE 2
set ::JTAG_INST_BYPASS -1
set ::JTAG_INST_REQUEST 8
set ::JTAG_INST_RESPONSE 9
set ::JTAG_INST_NUM_REQUEST 10
set ::JTAG_INST_NUM_RESPONSE 11

# reg jtag.request
set ::BW_JTAG_REQUEST 32

# reg jtag.response
set ::BW_JTAG_RESPONSE 32

# reg jtag_cmd
set ::BW_JTAG_CMD 2
set ::JTAG_CMD_SYSTEM_READ 0
set ::JTAG_CMD_SYSTEM_WRITE 1
set ::JTAG_CMD_MEMORY_READ 2
set ::JTAG_CMD_MEMORY_WRITE 3

# reg jtag_result
set ::BW_JTAG_RESULT 2
set ::JTAG_RESULT_OKAY 0
set ::JTAG_RESULT_ERROR 1
set ::JTAG_RESULT_BUSY 2

