# total
set ::BW_MMAP_OFFSET_ERVP_EXTERNAL_PERI_GROUP 12
set ::ERVP_EXTERNAL_PERI_GROUP_ADDR_INTERVAL 8
set ::BW_UNUSED_ERVP_EXTERNAL_PERI_GROUP 3
set ::NUM_ERVP_EXTERNAL_PERI_GROUP_SUBMODULE 12
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC 0
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC 0x0
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_UART0 1
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_UART0 0x100
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_UART1 2
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_UART1 0x200
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_UART2 3
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_UART2 0x300
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_UART3 4
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_UART3 0x400
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_I2C0 5
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_I2C0 0x500
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_I2C1 6
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_I2C1 0x600
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_I2C2 7
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_I2C2 0x700
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_I2C3 8
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_I2C3 0x800
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_SPI 9
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPI 0x900
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_GPIO 10
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO 0xa00
set ::SUBMODULE_INDEX_ERVP_EXTERNAL_PERI_GROUP_SPIO 11
set ::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO 0xb00

# submodule epg_misc
set ::BW_MMAP_SUBOFFSET_EPG_MISC 7
set ::BW_UNUSED_EPG_MISC 3
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG00 0x0
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG01 0x8
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG02 0x10
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG03 0x18
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG04 0x20
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG05 0x28
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG06 0x30
set ::MMAP_SUBOFFSET_EPG_MISC_EXTREG07 0x38
set ::MMAP_SUBOFFSET_EPG_MISC_GPIO_TICK_CFG 0x40

set ::MMAP_OFFSET_EPG_MISC_EXTREG00 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG00]
set ::MMAP_OFFSET_EPG_MISC_EXTREG01 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG01]
set ::MMAP_OFFSET_EPG_MISC_EXTREG02 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG02]
set ::MMAP_OFFSET_EPG_MISC_EXTREG03 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG03]
set ::MMAP_OFFSET_EPG_MISC_EXTREG04 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG04]
set ::MMAP_OFFSET_EPG_MISC_EXTREG05 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG05]
set ::MMAP_OFFSET_EPG_MISC_EXTREG06 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG06]
set ::MMAP_OFFSET_EPG_MISC_EXTREG07 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_EXTREG07]
set ::MMAP_OFFSET_EPG_MISC_GPIO_TICK_CFG [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_EPG_MISC + $::MMAP_SUBOFFSET_EPG_MISC_GPIO_TICK_CFG]

# submodule uart0
set ::BW_MMAP_SUBOFFSET_UART0 8
set ::BW_UNUSED_UART0 3


# submodule uart1
set ::BW_MMAP_SUBOFFSET_UART1 8
set ::BW_UNUSED_UART1 3


# submodule uart2
set ::BW_MMAP_SUBOFFSET_UART2 8
set ::BW_UNUSED_UART2 3


# submodule uart3
set ::BW_MMAP_SUBOFFSET_UART3 8
set ::BW_UNUSED_UART3 3


# submodule i2c0
set ::BW_MMAP_SUBOFFSET_I2C0 8
set ::BW_UNUSED_I2C0 3


# submodule i2c1
set ::BW_MMAP_SUBOFFSET_I2C1 8
set ::BW_UNUSED_I2C1 3


# submodule i2c2
set ::BW_MMAP_SUBOFFSET_I2C2 8
set ::BW_UNUSED_I2C2 3


# submodule i2c3
set ::BW_MMAP_SUBOFFSET_I2C3 8
set ::BW_UNUSED_I2C3 3


# submodule spi
set ::BW_MMAP_SUBOFFSET_SPI 8
set ::BW_UNUSED_SPI 3


# submodule gpio
set ::BW_MMAP_SUBOFFSET_GPIO 7
set ::BW_UNUSED_GPIO 3
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO00 0x0
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO01 0x8
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO02 0x10
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO03 0x18
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO04 0x20
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO05 0x28
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO06 0x30
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO07 0x38
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO08 0x40
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO09 0x48
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO10 0x50
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO11 0x58
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO12 0x60
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO13 0x68
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO14 0x70
set ::MMAP_SUBOFFSET_GPIO_USER_GPIO15 0x78

set ::MMAP_OFFSET_GPIO_USER_GPIO00 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO00]
set ::MMAP_OFFSET_GPIO_USER_GPIO01 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO01]
set ::MMAP_OFFSET_GPIO_USER_GPIO02 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO02]
set ::MMAP_OFFSET_GPIO_USER_GPIO03 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO03]
set ::MMAP_OFFSET_GPIO_USER_GPIO04 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO04]
set ::MMAP_OFFSET_GPIO_USER_GPIO05 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO05]
set ::MMAP_OFFSET_GPIO_USER_GPIO06 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO06]
set ::MMAP_OFFSET_GPIO_USER_GPIO07 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO07]
set ::MMAP_OFFSET_GPIO_USER_GPIO08 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO08]
set ::MMAP_OFFSET_GPIO_USER_GPIO09 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO09]
set ::MMAP_OFFSET_GPIO_USER_GPIO10 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO10]
set ::MMAP_OFFSET_GPIO_USER_GPIO11 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO11]
set ::MMAP_OFFSET_GPIO_USER_GPIO12 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO12]
set ::MMAP_OFFSET_GPIO_USER_GPIO13 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO13]
set ::MMAP_OFFSET_GPIO_USER_GPIO14 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO14]
set ::MMAP_OFFSET_GPIO_USER_GPIO15 [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_GPIO + $::MMAP_SUBOFFSET_GPIO_USER_GPIO15]

# submodule spio
set ::BW_MMAP_SUBOFFSET_SPIO 7
set ::BW_UNUSED_SPIO 3
set ::MMAP_SUBOFFSET_SPIO_OLED_DCSEL 0x0
set ::MMAP_SUBOFFSET_SPIO_OLED_RSTNN 0x8
set ::MMAP_SUBOFFSET_SPIO_OLED_VBAT 0x10
set ::MMAP_SUBOFFSET_SPIO_OLED_VDD 0x18
set ::MMAP_SUBOFFSET_SPIO_WIFI_RSTNN 0x20
set ::MMAP_SUBOFFSET_SPIO_WIFI_WP 0x28
set ::MMAP_SUBOFFSET_SPIO_WIFI_HIBERNATE 0x30
set ::MMAP_SUBOFFSET_SPIO_WIFI_ITR_CLEAR 0x38
set ::MMAP_SUBOFFSET_SPIO_WIFI_ITR_PENDING 0x40
set ::MMAP_SUBOFFSET_SPIO_SPI_CS_ACTIVE_LOW 0x48
set ::MMAP_SUBOFFSET_SPIO_SPI_SELECT 0x50
set ::MMAP_SUBOFFSET_SPIO_AIOIF_CONFIG 0x58
set ::MMAP_SUBOFFSET_SPIO_SERIAL_COMM_CONTROL 0x60

set ::MMAP_OFFSET_SPIO_OLED_DCSEL [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_OLED_DCSEL]
set ::MMAP_OFFSET_SPIO_OLED_RSTNN [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_OLED_RSTNN]
set ::MMAP_OFFSET_SPIO_OLED_VBAT [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_OLED_VBAT]
set ::MMAP_OFFSET_SPIO_OLED_VDD [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_OLED_VDD]
set ::MMAP_OFFSET_SPIO_WIFI_RSTNN [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_WIFI_RSTNN]
set ::MMAP_OFFSET_SPIO_WIFI_WP [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_WIFI_WP]
set ::MMAP_OFFSET_SPIO_WIFI_HIBERNATE [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_WIFI_HIBERNATE]
set ::MMAP_OFFSET_SPIO_WIFI_ITR_CLEAR [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_WIFI_ITR_CLEAR]
set ::MMAP_OFFSET_SPIO_WIFI_ITR_PENDING [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_WIFI_ITR_PENDING]
set ::MMAP_OFFSET_SPIO_SPI_CS_ACTIVE_LOW [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_SPI_CS_ACTIVE_LOW]
set ::MMAP_OFFSET_SPIO_SPI_SELECT [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_SPI_SELECT]
set ::MMAP_OFFSET_SPIO_AIOIF_CONFIG [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_AIOIF_CONFIG]
set ::MMAP_OFFSET_SPIO_SERIAL_COMM_CONTROL [expr $::SUBMODULE_ADDR_ERVP_EXTERNAL_PERI_GROUP_SPIO + $::MMAP_SUBOFFSET_SPIO_SERIAL_COMM_CONTROL]

# reg spio.spi_cs_active_low
set ::BW_SPIO_SPI_CS_ACTIVE_LOW 32

# reg spio.serial_comm_control
set ::BW_SPIO_SERIAL_COMM_CONTROL 4
set ::SPIO_SERIAL_COMM_CONTROL_SPI_CLK_USER_OE 1
set ::SPIO_SERIAL_COMM_CONTROL_SPI_CLK_USER_VALUE 2
set ::SPIO_SERIAL_COMM_CONTROL_SPI_DQ0_USER_OE 4
set ::SPIO_SERIAL_COMM_CONTROL_SPI_DQ0_USER_VALUE 8
set ::SPIO_SERIAL_COMM_CONTROL_INDEX_SPI_CLK_USER_OE 0
set ::SPIO_SERIAL_COMM_CONTROL_INDEX_SPI_CLK_USER_VALUE 1
set ::SPIO_SERIAL_COMM_CONTROL_INDEX_SPI_DQ0_USER_OE 2
set ::SPIO_SERIAL_COMM_CONTROL_INDEX_SPI_DQ0_USER_VALUE 3
set ::SPIO_SERIAL_COMM_CONTROL_NONE 0

# reg epg_misc.extreg
set ::BW_EPG_MISC_EXTREG 32

# reg epg_misc.gpio_tick_cfg
set ::BW_EPG_MISC_GPIO_TICK_CFG 16

# reg gpio.user_gpio
set ::BW_GPIO_USER_GPIO 32

# reg spio.oled_dcsel
set ::BW_SPIO_OLED_DCSEL 1

# reg spio.oled_rstnn
set ::BW_SPIO_OLED_RSTNN 1

# reg spio.oled_vbat
set ::BW_SPIO_OLED_VBAT 1

# reg spio.oled_vdd
set ::BW_SPIO_OLED_VDD 1

# reg spio.wifi_rstnn
set ::BW_SPIO_WIFI_RSTNN 1

# reg spio.wifi_wp
set ::BW_SPIO_WIFI_WP 1

# reg spio.wifi_hibernate
set ::BW_SPIO_WIFI_HIBERNATE 1

# reg spio.wifi_itr_clear
set ::BW_SPIO_WIFI_ITR_CLEAR 1

# reg spio.wifi_itr_pending
set ::BW_SPIO_WIFI_ITR_PENDING 1

# reg spio.spi_select
set ::BW_SPIO_SPI_SELECT 32

# reg spio.aioif_config
set ::BW_SPIO_AIOIF_CONFIG 32

# reg oled_dc_sel
set ::BW_OLED_DC_SEL 1
set ::OLED_DC_SEL_COMMAND 0
set ::OLED_DC_SEL_DATA 1
set ::OLED_DC_SEL_INDEX_DATA 0

# reg ocd_flash_cmd
set ::BW_OCD_FLASH_CMD 3
set ::OCD_FLASH_CMD_IDLE 0
set ::OCD_FLASH_CMD_CHECK 1
set ::OCD_FLASH_CMD_ERASE 2
set ::OCD_FLASH_CMD_READ 3
set ::OCD_FLASH_CMD_WRITE 4
set ::OCD_FLASH_CMD_INDEX_CHECK 0
set ::OCD_FLASH_CMD_INDEX_ERASE 1
set ::OCD_FLASH_CMD_INDEX_WRITE 2

# reg boot_status
set ::BW_BOOT_STATUS 2
set ::BOOT_STATUS_RESETED 0
set ::BOOT_STATUS_APP_LOAD 1
set ::BOOT_STATUS_ALL_READY 2
set ::BOOT_STATUS_INDEX_APP_LOAD 0
set ::BOOT_STATUS_INDEX_ALL_READY 1

# reg gpio_config
set ::BW_GPIO_CONFIG 5
set ::GPIO_CONFIG_IS_SIGNED_VALUE 1
set ::GPIO_CONFIG_IS_OUTPUT_PORT 2
set ::GPIO_CONFIG_ITR_ENABLE 4
set ::GPIO_CONFIG_DEBOUNCE_ENABLE 8
set ::GPIO_CONFIG_USER_IO_SELECT 16
set ::GPIO_CONFIG_INDEX_IS_SIGNED_VALUE 0
set ::GPIO_CONFIG_INDEX_IS_OUTPUT_PORT 1
set ::GPIO_CONFIG_INDEX_ITR_ENABLE 2
set ::GPIO_CONFIG_INDEX_DEBOUNCE_ENABLE 3
set ::GPIO_CONFIG_INDEX_USER_IO_SELECT 4
set ::GPIO_CONFIG_NONE 0

# reg gpio_cmd
set ::BW_GPIO_CMD 4
set ::GPIO_CMD_WE_VALUE 1
set ::GPIO_CMD_WE_CONFIG 2
set ::GPIO_CMD_WE_ITR_COND 4
set ::GPIO_CMD_CLEAR_ITR 8
set ::GPIO_CMD_INDEX_WE_VALUE 0
set ::GPIO_CMD_INDEX_WE_CONFIG 1
set ::GPIO_CMD_INDEX_WE_ITR_COND 2
set ::GPIO_CMD_INDEX_CLEAR_ITR 3
set ::GPIO_CMD_NONE 0

# reg aioif_type
set ::BW_AIOIF_TYPE 4
set ::AIOIF_TYPE_GPIO 1
set ::AIOIF_TYPE_I2C 2
set ::AIOIF_TYPE_SPI 4
set ::AIOIF_TYPE_UART 8
set ::AIOIF_TYPE_INDEX_GPIO 0
set ::AIOIF_TYPE_INDEX_I2C 1
set ::AIOIF_TYPE_INDEX_SPI 2
set ::AIOIF_TYPE_INDEX_UART 3
set ::AIOIF_TYPE_NONE 0

# reg gpio_value
set ::BW_GPIO_VALUE 16

