# total
set ::BW_MMAP_OFFSET_ERVP_FUSE_BOX 5
set ::ERVP_FUSE_BOX_ADDR_INTERVAL 8
set ::BW_UNUSED_ERVP_FUSE_BOX 3
set ::NUM_ERVP_FUSE_BOX_SUBMODULE 1

# submodule fuse_box
set ::MMAP_SUBOFFSET_FUSE_BOX_CORE_CLOCK_CMD 0x0
set ::MMAP_SUBOFFSET_FUSE_BOX_USER_CLOCK_CMD 0x8
set ::MMAP_SUBOFFSET_FUSE_BOX_SYSTEM_CMD 0x10

set ::MMAP_OFFSET_FUSE_BOX_CORE_CLOCK_CMD ($MMAP_SUBOFFSET_FUSE_BOX_CORE_CLOCK_CMD)
set ::MMAP_OFFSET_FUSE_BOX_USER_CLOCK_CMD ($MMAP_SUBOFFSET_FUSE_BOX_USER_CLOCK_CMD)
set ::MMAP_OFFSET_FUSE_BOX_SYSTEM_CMD ($MMAP_SUBOFFSET_FUSE_BOX_SYSTEM_CMD)

# reg fuse_box.core_clock_cmd
set ::BW_FUSE_BOX_CORE_CLOCK_CMD 32

# reg fuse_box.user_clock_cmd
set ::BW_FUSE_BOX_USER_CLOCK_CMD 32

# reg fuse_box.system_cmd
set ::BW_FUSE_BOX_SYSTEM_CMD 32

# reg clock_cmd
set ::BW_CLOCK_CMD 3
set ::CLOCK_CMD_WAKEUP 0
set ::CLOCK_CMD_SLEEP 1
set ::CLOCK_CMD_DISABLE 3
set ::CLOCK_CMD_WFI 5

