# total
set ::BW_MMAP_OFFSET_ERVP_PLATFORM_CONTROLLER 18
set ::ERVP_PLATFORM_CONTROLLER_ADDR_INTERVAL 8
set ::BW_UNUSED_ERVP_PLATFORM_CONTROLLER 3
set ::NUM_ERVP_PLATFORM_CONTROLLER_SUBMODULE 4
set ::SUBMODULE_INDEX_ERVP_PLATFORM_CONTROLLER_RESET 0
set ::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_RESET 0x0
set ::SUBMODULE_INDEX_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER 1
set ::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER 0x10000
set ::SUBMODULE_INDEX_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO 2
set ::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO 0x20000
set ::SUBMODULE_INDEX_ERVP_PLATFORM_CONTROLLER_EXTERNAL 3
set ::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_EXTERNAL 0x30000

# submodule reset
set ::BW_MMAP_SUBOFFSET_RESET 5
set ::BW_UNUSED_RESET 3
set ::MMAP_SUBOFFSET_RESET_CMD 0x0
set ::MMAP_SUBOFFSET_RESET_MASK 0x8
set ::MMAP_SUBOFFSET_RESET_SEQUENCE 0x10

set ::MMAP_OFFSET_RESET_CMD [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_RESET + $::MMAP_SUBOFFSET_RESET_CMD]
set ::MMAP_OFFSET_RESET_MASK [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_RESET + $::MMAP_SUBOFFSET_RESET_MASK]
set ::MMAP_OFFSET_RESET_SEQUENCE [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_RESET + $::MMAP_SUBOFFSET_RESET_SEQUENCE]

# submodule platform_register
set ::BW_MMAP_SUBOFFSET_PLATFORM_REGISTER 8
set ::BW_UNUSED_PLATFORM_REGISTER 3
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_BOOT_MODE 0x0
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_INITIALIZED 0x8
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_SIM_ENV 0x10
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_JTAG_SELECT 0x18
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_BOOT_STATUS 0x20
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_APP_ADDR 0x28
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_PROC_AUTO_ID 0x30
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_PROC_STATUS 0x38
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC00 0x40
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC01 0x48
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC02 0x50
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC03 0x58
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST00 0x60
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST01 0x68
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST02 0x70
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST03 0x78
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_IMP_TYPE 0x80
set ::MMAP_SUBOFFSET_PLATFORM_REGISTER_FLASH_BASE_ADDR 0x88

set ::MMAP_OFFSET_PLATFORM_REGISTER_BOOT_MODE [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_BOOT_MODE]
set ::MMAP_OFFSET_PLATFORM_REGISTER_INITIALIZED [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_INITIALIZED]
set ::MMAP_OFFSET_PLATFORM_REGISTER_SIM_ENV [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_SIM_ENV]
set ::MMAP_OFFSET_PLATFORM_REGISTER_JTAG_SELECT [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_JTAG_SELECT]
set ::MMAP_OFFSET_PLATFORM_REGISTER_BOOT_STATUS [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_BOOT_STATUS]
set ::MMAP_OFFSET_PLATFORM_REGISTER_APP_ADDR [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_APP_ADDR]
set ::MMAP_OFFSET_PLATFORM_REGISTER_PROC_AUTO_ID [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_PROC_AUTO_ID]
set ::MMAP_OFFSET_PLATFORM_REGISTER_PROC_STATUS [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_PROC_STATUS]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC00]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC01]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC02]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_PC03]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST00]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST01]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST02]
set ::MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_CORE_INST03]
set ::MMAP_OFFSET_PLATFORM_REGISTER_IMP_TYPE [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_IMP_TYPE]
set ::MMAP_OFFSET_PLATFORM_REGISTER_FLASH_BASE_ADDR [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER + $::MMAP_SUBOFFSET_PLATFORM_REGISTER_FLASH_BASE_ADDR]

# submodule design_info
set ::BW_MMAP_SUBOFFSET_DESIGN_INFO 8
set ::BW_UNUSED_DESIGN_INFO 3
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE00 0x0
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE01 0x8
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE02 0x10
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE03 0x18
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE04 0x20
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE05 0x28
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE06 0x30
set ::MMAP_SUBOFFSET_DESIGN_INFO_DATE07 0x38
set ::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME00 0x40
set ::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME01 0x48
set ::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME02 0x50
set ::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME03 0x58
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME00 0x60
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME01 0x68
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME02 0x70
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME03 0x78
set ::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME00 0x80
set ::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME01 0x88
set ::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME02 0x90
set ::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME03 0x98
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION00 0xa0
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION01 0xa8
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION02 0xb0
set ::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION03 0xb8
set ::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION00 0xc0
set ::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION01 0xc8
set ::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION02 0xd0
set ::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION03 0xd8

set ::MMAP_OFFSET_DESIGN_INFO_DATE00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE00]
set ::MMAP_OFFSET_DESIGN_INFO_DATE01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE01]
set ::MMAP_OFFSET_DESIGN_INFO_DATE02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE02]
set ::MMAP_OFFSET_DESIGN_INFO_DATE03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE03]
set ::MMAP_OFFSET_DESIGN_INFO_DATE04 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE04]
set ::MMAP_OFFSET_DESIGN_INFO_DATE05 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE05]
set ::MMAP_OFFSET_DESIGN_INFO_DATE06 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE06]
set ::MMAP_OFFSET_DESIGN_INFO_DATE07 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DATE07]
set ::MMAP_OFFSET_DESIGN_INFO_USERNAME00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME00]
set ::MMAP_OFFSET_DESIGN_INFO_USERNAME01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME01]
set ::MMAP_OFFSET_DESIGN_INFO_USERNAME02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME02]
set ::MMAP_OFFSET_DESIGN_INFO_USERNAME03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_USERNAME03]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME00]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME01]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME02]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_NAME03]
set ::MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME00]
set ::MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME01]
set ::MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME02]
set ::MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_PLATFORM_NAME03]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION00]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION01]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION02]
set ::MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_HOME_GIT_VERSION03]
set ::MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION00 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION00]
set ::MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION01 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION01]
set ::MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION02 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION02]
set ::MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION03 [expr $::SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO + $::MMAP_SUBOFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION03]

# submodule external
set ::BW_MMAP_SUBOFFSET_EXTERNAL 16
set ::BW_UNUSED_EXTERNAL 3


# reg reset.cmd
set ::BW_RESET_CMD 3
set ::RESET_CMD_IDLE 0
set ::RESET_CMD_INIT 1
set ::RESET_CMD_AUTO_INCR 2
set ::RESET_CMD_NEXT_STEP 3
set ::RESET_CMD_IDLE_WITH_ERROR 4
set ::RESET_CMD_INDEX_INIT 0
set ::RESET_CMD_INDEX_AUTO_INCR 1
set ::RESET_CMD_INDEX_IDLE_WITH_ERROR 2

# reg reset.mask
set ::BW_RESET_MASK 32

# reg reset.sequence
set ::BW_RESET_SEQUENCE 32

# reg platform_register.boot_mode
set ::BW_PLATFORM_REGISTER_BOOT_MODE 4

# reg platform_register.initialized
set ::BW_PLATFORM_REGISTER_INITIALIZED 1

# reg platform_register.sim_env
set ::BW_PLATFORM_REGISTER_SIM_ENV 1

# reg platform_register.jtag_select
set ::BW_PLATFORM_REGISTER_JTAG_SELECT 1

# reg platform_register.boot_status
set ::BW_PLATFORM_REGISTER_BOOT_STATUS 32

# reg platform_register.app_addr
set ::BW_PLATFORM_REGISTER_APP_ADDR 32

# reg platform_register.proc_auto_id
set ::BW_PLATFORM_REGISTER_PROC_AUTO_ID 32

# reg platform_register.proc_status
set ::BW_PLATFORM_REGISTER_PROC_STATUS 32

# reg platform_register.core_pc
set ::BW_PLATFORM_REGISTER_CORE_PC 32

# reg platform_register.core_inst
set ::BW_PLATFORM_REGISTER_CORE_INST 32

# reg platform_register.imp_type
set ::BW_PLATFORM_REGISTER_IMP_TYPE 32

# reg platform_register.flash_base_addr
set ::BW_PLATFORM_REGISTER_FLASH_BASE_ADDR 32

# reg design_info.date
set ::BW_DESIGN_INFO_DATE 32

# reg design_info.username
set ::BW_DESIGN_INFO_USERNAME 32

# reg design_info.home_git_name
set ::BW_DESIGN_INFO_HOME_GIT_NAME 32

# reg design_info.platform_name
set ::BW_DESIGN_INFO_PLATFORM_NAME 32

# reg design_info.home_git_version
set ::BW_DESIGN_INFO_HOME_GIT_VERSION 32

# reg design_info.devkit_git_version
set ::BW_DESIGN_INFO_DEVKIT_GIT_VERSION 32

# reg boot_mode
set ::BW_BOOT_MODE 1
set ::BOOT_MODE_OCD 0
set ::BOOT_MODE_STAND_ALONE 1
set ::BOOT_MODE_INDEX_STAND_ALONE 0

# reg boot_status
set ::BW_BOOT_STATUS 2
set ::BOOT_STATUS_RESETED 0
set ::BOOT_STATUS_APP_LOAD 1
set ::BOOT_STATUS_ALL_READY 2
set ::BOOT_STATUS_INDEX_APP_LOAD 0
set ::BOOT_STATUS_INDEX_ALL_READY 1

# reg jtag_select
set ::BW_JTAG_SELECT 1
set ::JTAG_SELECT_NOC 0
set ::JTAG_SELECT_CORE 1
set ::JTAG_SELECT_INDEX_CORE 0

# reg imp_type
set ::BW_IMP_TYPE 2
set ::IMP_TYPE_RTL 0
set ::IMP_TYPE_FPGA 1
set ::IMP_TYPE_CHIP 2
set ::IMP_TYPE_VP 3
set ::IMP_TYPE_INDEX_FPGA 0
set ::IMP_TYPE_INDEX_CHIP 1

