# total
set ::BW_MMAP_OFFSET_MUNOC 10
set ::MUNOC_ADDR_INTERVAL 8
set ::BW_UNUSED_MUNOC 3
set ::NUM_MUNOC_SUBMODULE 3
set ::SUBMODULE_INDEX_MUNOC_INFO 0
set ::SUBMODULE_ADDR_MUNOC_INFO 0x0
set ::SUBMODULE_INDEX_MUNOC_ELOG 1
set ::SUBMODULE_ADDR_MUNOC_ELOG 0x100
set ::SUBMODULE_INDEX_MUNOC_CONTROLLER 2
set ::SUBMODULE_ADDR_MUNOC_CONTROLLER 0x200

# submodule info
set ::BW_MMAP_SUBOFFSET_INFO 7
set ::BW_UNUSED_INFO 3
set ::MMAP_SUBOFFSET_INFO_VERSION0 0x0
set ::MMAP_SUBOFFSET_INFO_VERSION1 0x8
set ::MMAP_SUBOFFSET_INFO_VERSION2 0x10
set ::MMAP_SUBOFFSET_INFO_VERSION3 0x18
set ::MMAP_SUBOFFSET_INFO_CONFIG0 0x20
set ::MMAP_SUBOFFSET_INFO_CONFIG1 0x28
set ::MMAP_SUBOFFSET_INFO_NUM_MASTER 0x30
set ::MMAP_SUBOFFSET_INFO_NUM_SLAVE 0x38
set ::MMAP_SUBOFFSET_INFO_SELF_ID 0x40

set ::MMAP_OFFSET_INFO_VERSION0 [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_VERSION0]
set ::MMAP_OFFSET_INFO_VERSION1 [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_VERSION1]
set ::MMAP_OFFSET_INFO_VERSION2 [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_VERSION2]
set ::MMAP_OFFSET_INFO_VERSION3 [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_VERSION3]
set ::MMAP_OFFSET_INFO_CONFIG0 [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_CONFIG0]
set ::MMAP_OFFSET_INFO_CONFIG1 [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_CONFIG1]
set ::MMAP_OFFSET_INFO_NUM_MASTER [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_NUM_MASTER]
set ::MMAP_OFFSET_INFO_NUM_SLAVE [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_NUM_SLAVE]
set ::MMAP_OFFSET_INFO_SELF_ID [expr $::SUBMODULE_ADDR_MUNOC_INFO + $::MMAP_SUBOFFSET_INFO_SELF_ID]

# submodule elog
set ::BW_MMAP_SUBOFFSET_ELOG 6
set ::BW_UNUSED_ELOG 3
set ::MMAP_SUBOFFSET_ELOG_COUNT 0x0
set ::MMAP_SUBOFFSET_ELOG_VALID 0x8
set ::MMAP_SUBOFFSET_ELOG_RW 0x10
set ::MMAP_SUBOFFSET_ELOG_ADDR 0x18
set ::MMAP_SUBOFFSET_ELOG_MASTER 0x20

set ::MMAP_OFFSET_ELOG_COUNT [expr $::SUBMODULE_ADDR_MUNOC_ELOG + $::MMAP_SUBOFFSET_ELOG_COUNT]
set ::MMAP_OFFSET_ELOG_VALID [expr $::SUBMODULE_ADDR_MUNOC_ELOG + $::MMAP_SUBOFFSET_ELOG_VALID]
set ::MMAP_OFFSET_ELOG_RW [expr $::SUBMODULE_ADDR_MUNOC_ELOG + $::MMAP_SUBOFFSET_ELOG_RW]
set ::MMAP_OFFSET_ELOG_ADDR [expr $::SUBMODULE_ADDR_MUNOC_ELOG + $::MMAP_SUBOFFSET_ELOG_ADDR]
set ::MMAP_OFFSET_ELOG_MASTER [expr $::SUBMODULE_ADDR_MUNOC_ELOG + $::MMAP_SUBOFFSET_ELOG_MASTER]

# submodule controller
set ::BW_MMAP_SUBOFFSET_CONTROLLER 8
set ::BW_UNUSED_CONTROLLER 3
set ::MMAP_SUBOFFSET_CONTROLLER_NAME0 0x0
set ::MMAP_SUBOFFSET_CONTROLLER_NAME1 0x8
set ::MMAP_SUBOFFSET_CONTROLLER_NAME2 0x10
set ::MMAP_SUBOFFSET_CONTROLLER_NAME3 0x18
set ::MMAP_SUBOFFSET_CONTROLLER_NAME4 0x20
set ::MMAP_SUBOFFSET_CONTROLLER_NAME5 0x28
set ::MMAP_SUBOFFSET_CONTROLLER_NAME6 0x30
set ::MMAP_SUBOFFSET_CONTROLLER_NAME7 0x38
set ::MMAP_SUBOFFSET_CONTROLLER_TYPE0 0x40
set ::MMAP_SUBOFFSET_CONTROLLER_TYPE1 0x48
set ::MMAP_SUBOFFSET_CONTROLLER_NODEID 0x50
set ::MMAP_SUBOFFSET_CONTROLLER_FNI_STATE 0x58
set ::MMAP_SUBOFFSET_CONTROLLER_BNI_STATE 0x60
set ::MMAP_SUBOFFSET_CONTROLLER_MONITOR_ENABLE 0x68
set ::MMAP_SUBOFFSET_CONTROLLER_EXCLUDE 0x70
set ::MMAP_SUBOFFSET_CONTROLLER_IP_TIMEOUT 0x78
set ::MMAP_SUBOFFSET_CONTROLLER_NOC_TIMEOUT 0x80
set ::MMAP_SUBOFFSET_CONTROLLER_ROUTING_ERROR 0x88
set ::MMAP_SUBOFFSET_CONTROLLER_BANDWIDTH 0x90
set ::MMAP_SUBOFFSET_CONTROLLER_PROTOCOL_VIOLATION 0x98

set ::MMAP_OFFSET_CONTROLLER_NAME0 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME0]
set ::MMAP_OFFSET_CONTROLLER_NAME1 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME1]
set ::MMAP_OFFSET_CONTROLLER_NAME2 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME2]
set ::MMAP_OFFSET_CONTROLLER_NAME3 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME3]
set ::MMAP_OFFSET_CONTROLLER_NAME4 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME4]
set ::MMAP_OFFSET_CONTROLLER_NAME5 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME5]
set ::MMAP_OFFSET_CONTROLLER_NAME6 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME6]
set ::MMAP_OFFSET_CONTROLLER_NAME7 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NAME7]
set ::MMAP_OFFSET_CONTROLLER_TYPE0 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_TYPE0]
set ::MMAP_OFFSET_CONTROLLER_TYPE1 [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_TYPE1]
set ::MMAP_OFFSET_CONTROLLER_NODEID [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NODEID]
set ::MMAP_OFFSET_CONTROLLER_FNI_STATE [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_FNI_STATE]
set ::MMAP_OFFSET_CONTROLLER_BNI_STATE [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_BNI_STATE]
set ::MMAP_OFFSET_CONTROLLER_MONITOR_ENABLE [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_MONITOR_ENABLE]
set ::MMAP_OFFSET_CONTROLLER_EXCLUDE [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_EXCLUDE]
set ::MMAP_OFFSET_CONTROLLER_IP_TIMEOUT [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_IP_TIMEOUT]
set ::MMAP_OFFSET_CONTROLLER_NOC_TIMEOUT [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_NOC_TIMEOUT]
set ::MMAP_OFFSET_CONTROLLER_ROUTING_ERROR [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_ROUTING_ERROR]
set ::MMAP_OFFSET_CONTROLLER_BANDWIDTH [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_BANDWIDTH]
set ::MMAP_OFFSET_CONTROLLER_PROTOCOL_VIOLATION [expr $::SUBMODULE_ADDR_MUNOC_CONTROLLER + $::MMAP_SUBOFFSET_CONTROLLER_PROTOCOL_VIOLATION]

# reg info.version0
set ::BW_INFO_VERSION0 32

# reg info.version1
set ::BW_INFO_VERSION1 32

# reg info.version2
set ::BW_INFO_VERSION2 32

# reg info.version3
set ::BW_INFO_VERSION3 32

# reg info.config0
set ::BW_INFO_CONFIG0 32

# reg info.config1
set ::BW_INFO_CONFIG1 32

# reg info.num_master
set ::BW_INFO_NUM_MASTER 32

# reg info.num_slave
set ::BW_INFO_NUM_SLAVE 32

# reg info.self_id
set ::BW_INFO_SELF_ID 32

# reg elog.count
set ::BW_ELOG_COUNT 32

# reg elog.valid
set ::BW_ELOG_VALID 32

# reg elog.rw
set ::BW_ELOG_RW 32

# reg elog.addr
set ::BW_ELOG_ADDR 32

# reg elog.master
set ::BW_ELOG_MASTER 32

# reg controller.name0
set ::BW_CONTROLLER_NAME0 32

# reg controller.name1
set ::BW_CONTROLLER_NAME1 32

# reg controller.name2
set ::BW_CONTROLLER_NAME2 32

# reg controller.name3
set ::BW_CONTROLLER_NAME3 32

# reg controller.name4
set ::BW_CONTROLLER_NAME4 32

# reg controller.name5
set ::BW_CONTROLLER_NAME5 32

# reg controller.name6
set ::BW_CONTROLLER_NAME6 32

# reg controller.name7
set ::BW_CONTROLLER_NAME7 32

# reg controller.type0
set ::BW_CONTROLLER_TYPE0 32

# reg controller.type1
set ::BW_CONTROLLER_TYPE1 32

# reg controller.nodeid
set ::BW_CONTROLLER_NODEID 32

# reg controller.fni_state
set ::BW_CONTROLLER_FNI_STATE 32

# reg controller.bni_state
set ::BW_CONTROLLER_BNI_STATE 32

# reg controller.monitor_enable
set ::BW_CONTROLLER_MONITOR_ENABLE 32

# reg controller.exclude
set ::BW_CONTROLLER_EXCLUDE 32

# reg controller.ip_timeout
set ::BW_CONTROLLER_IP_TIMEOUT 32

# reg controller.noc_timeout
set ::BW_CONTROLLER_NOC_TIMEOUT 32

# reg controller.routing_error
set ::BW_CONTROLLER_ROUTING_ERROR 32

# reg controller.bandwidth
set ::BW_CONTROLLER_BANDWIDTH 32

# reg controller.protocol_violation
set ::BW_CONTROLLER_PROTOCOL_VIOLATION 32

